### PR TITLE
Update Request (Listen plz)

### PR DESCRIPTION
**Pull request by NathanBollard**
> I feel like it’s enough “re-names”.

_Originally posted by @rxzyx in https://github.com/rxzyx/Blooket-Hacks/issues/192#issuecomment-1309073626_

## Reasoning

My fork has 7 commits (discluding the conflict fix, [22481b9](https://github.com/rxzyx/Blooket-Hacks/pull/196/commits/22481b9b8621c30b0b4cf065a7a2c53f37aae3f0)), and I am requesting for those commits to be added to this repository.

@BlooketHeck did most of the renames, but it'll be the last two for the made-up "Set" rule. All the "Add"s (discluding [Add Mega Bots.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Factory/Add%20Mega%20Bots.js)) and "Get"s are renamed to "Set", except those two: [Get Blooks.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Blook%20Rush/Get%20Blooks.js) and [Get Defense.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Blook%20Rush/Get%20Defense.js). It also updates more than you think in [README.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/README.md). (Hereby, this pull request's commits also fix an invalid link in [README.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/README.md))In [README.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/README.md), there was NO list of hacks for [Blook Rush](https://github.com/rxzyx/Blooket-Hacks/tree/main/Blook%20Rush) nor [Crazy Kingdom](https://github.com/rxzyx/Blooket-Hacks/tree/main/Crazy%20Kingdom). I added them, and organized all the gamemode categories in the current Blooket host order. I also alphabetized all the hacks for each category, and updated <i>most</i> of the descriptions. For the people who look for [Blook Rush](https://github.com/rxzyx/Blooket-Hacks/tree/main/Blook%20Rush) hacks, it looks more appealing to them since it was recently updated, and let's them know it more likely to work than if it was updated last over 5 months ago. Those are some of the reasons why you should merge this pull request. To see all of the changes, see [#196 files](https://github.com/rxzyx/Blooket-Hacks/pull/196/files). It was mainly for [README.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/README.md), so I'd suggest also seeing [this](https://github.com/rxzyx/Blooket-Hacks/blob/11dd9ce8398705156df014407afd2f93c9adb141/README.md).

### CODE REVIEW

**Comment by BlooketHeck** [comment]
I feel the update readme commits are a bit much

**Comment by ZackiBoiz** [comment]
> > I feel like it’s enough “re-names”.
> 
> _Originally posted by @rxzyx in [#192 (comment)](https://github.com/rxzyx/Blooket-Hacks/pull/192#issuecomment-1309073626)_
> 
> ## Reasoning
> My fork has 7 commits (discluding the conflict fix, [22481b9](https://github.com/rxzyx/Blooket-Hacks/pull/196/commits/22481b9b8621c30b0b4cf065a7a2c53f37aae3f0)), and I am requesting for those commits to be added to this repository.
> 
> @BlooketHeck did most of the renames, but it'll be the last two for the made-up "Set" rule. All the "Add"s (discluding [Add Mega Bots.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Factory/Add%20Mega%20Bots.js)) and "Get"s are renamed to "Set", except those two: [Get Blooks.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Blook%20Rush/Get%20Blooks.js) and [Get Defense.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Blook%20Rush/Get%20Defense.js). It also updates more than you think in [README.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/README.md). (Hereby, this pull request's commits also fix an invalid link in [README.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/README.md))In [README.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/README.md), there was NO list of hacks for [Blook Rush](https://github.com/rxzyx/Blooket-Hacks/tree/main/Blook%20Rush) nor [Crazy Kingdom](https://github.com/rxzyx/Blooket-Hacks/tree/main/Crazy%20Kingdom). I added them, and organized all the gamemode categories in the current Blooket host order. I also alphabetized all the hacks for each category, and updated most of the descriptions. For the people who look for [Blook Rush](https://github.com/rxzyx/Blooket-Hacks/tree/main/Blook%20Rush) hacks, it looks more appealing to them since it was recently updated, and let's them know it more likely to work than if it was updated last over 5 months ago. Those are some of the reasons why you should merge this pull request. To see all of the changes, see [#196 files](https://github.com/rxzyx/Blooket-Hacks/pull/196/files). It was mainly for [README.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/README.md), so I'd suggest also seeing [this](https://github.com/rxzyx/Blooket-Hacks/blob/11dd9ce8398705156df014407afd2f93c9adb141/README.md).

Even though it is a bit too many `README.md` edits, it is good to see things alphabetized, and have neat descriptions.

**Comment by VillainsRule4000** [comment]
@NathanBollard Do you understand what a PR decline is? It's a thing saying your changes are not wanted. So stop making dupe PRs

**Comment by BlooketHeck** [comment]
I don't think this should be merged

**Comment by BlooketHeck** [comment]
> @NathanBollard Do you understand what a PR decline is? It's a thing saying your changes are not wanted. So stop making dupe PRs

This shouldn't be merged

**Comment by NathanBollard** [comment]
> @NathanBollard Do you understand what a PR decline is? It's a thing saying your changes are not wanted. So stop making dupe PRs

This is 8 commits, not 3 commits.

**Comment by NathanBollard** [comment]
> > > I feel like it’s enough “re-names”.
> > 
> > 
> > _Originally posted by @rxzyx in [#192 (comment)](https://github.com/rxzyx/Blooket-Hacks/pull/192#issuecomment-1309073626)_
> > ## Reasoning
> > My fork has 7 commits (discluding the conflict fix, [22481b9](https://github.com/rxzyx/Blooket-Hacks/pull/196/commits/22481b9b8621c30b0b4cf065a7a2c53f37aae3f0)), and I am requesting for those commits to be added to this repository.
> > @BlooketHeck did most of the renames, but it'll be the last two for the made-up "Set" rule. All the "Add"s (discluding [Add Mega Bots.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Factory/Add%20Mega%20Bots.js)) and "Get"s are renamed to "Set", except those two: [Get Blooks.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Blook%20Rush/Get%20Blooks.js) and [Get Defense.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Blook%20Rush/Get%20Defense.js). It also updates more than you think in [README.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/README.md). (Hereby, this pull request's commits also fix an invalid link in [README.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/README.md))In [README.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/README.md), there was NO list of hacks for [Blook Rush](https://github.com/rxzyx/Blooket-Hacks/tree/main/Blook%20Rush) nor [Crazy Kingdom](https://github.com/rxzyx/Blooket-Hacks/tree/main/Crazy%20Kingdom). I added them, and organized all the gamemode categories in the current Blooket host order. I also alphabetized all the hacks for each category, and updated most of the descriptions. For the people who look for [Blook Rush](https://github.com/rxzyx/Blooket-Hacks/tree/main/Blook%20Rush) hacks, it looks more appealing to them since it was recently updated, and let's them know it more likely to work than if it was updated last over 5 months ago. Those are some of the reasons why you should merge this pull request. To see all of the changes, see [#196 files](https://github.com/rxzyx/Blooket-Hacks/pull/196/files). It was mainly for [README.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/README.md), so I'd suggest also seeing [this](https://github.com/rxzyx/Blooket-Hacks/blob/11dd9ce8398705156df014407afd2f93c9adb141/README.md).
> 
> Even though it is a bit too many `README.md` edits, it is good to see things alphabetized, and have neat descriptions.

Thank you!

**Comment by VillainsRule4000** [comment]
> > @NathanBollard Do you understand what a PR decline is? It's a thing saying your changes are not wanted. So stop making dupe PRs
> 
> This is 8 commits, not 3 commits.

remind me who asked

**Comment by BlooketHeck** [comment]
> > > @NathanBollard Do you understand what a PR decline is? It's a thing saying your changes are not wanted. So stop making dupe PRs
> > 
> > 
> > This is 8 commits, not 3 commits.
> 
> remind me who asked

Ummmmmm... NOBODY

**Comment by chessmcface** [comment]
lol your forks are good @NathanBollard

**Comment by ZackiBoiz** [comment]
> > > > @NathanBollard Do you understand what a PR decline is? It's a thing saying your changes are not wanted. So stop making dupe PRs
> > > 
> > > 
> > > This is 8 commits, not 3 commits.
> > 
> > 
> > remind me who asked
> 
> Ummmmmm... NOBODY

Yeah, but does that matter?

**Comment by NathanBollard** [comment]
> lol your forks are good @NathanBollard

Thank you!

**Comment by NathanBollard** [comment]
> > > > > @NathanBollard Do you understand what a PR decline is? It's a thing saying your changes are not wanted. So stop making dupe PRs
> > > > 
> > > > 
> > > > This is 8 commits, not 3 commits.
> > > 
> > > 
> > > remind me who asked
> > 
> > 
> > Ummmmmm... NOBODY
> 
> Yeah, but does that matter?

Exactly. It doesn't.

**Comment by NathanBollard** [comment]
> > > > > @NathanBollard Do you understand what a PR decline is? It's a thing saying your changes are not wanted. So stop making dupe PRs
> > > > 
> > > > 
> > > > This is 8 commits, not 3 commits.
> > > 
> > > 
> > > remind me who asked
> > 
> > 
> > Ummmmmm... NOBODY
> 
> Yeah, but does that matter?

Exactly. It doesn't.

**Comment by VillainsRule4000** [comment]
no more renames

**Comment by chessmcface** [comment]
lol calm down guys

**Comment by NathanBollard** [comment]
> no more renames

no more fortnite no more cards no more 19 dollar cards

**Pull request merged**
