### PR TITLE
Update Add-Tokens-and-XP.js

### PR DESCRIPTION
**Pull request by Jude-Gideon**
## Description

Show the description of the hack **you made**.
I modified your hack so when ran at the end of the alert it shows - MADE BY RXZYX

## Code

Make sure the code was tested for any errors and if it works.
Works fine.

### CODE REVIEW

**Comment by Jude-Gideon** [comment]
Only made because people continuously steal your code.

**Comment by JayDaMan53** [comment]
This is pretty easy to change but it is good for people that don't know how to change it.

**Comment by mungK11** [comment]
the hack works just go on the join page and use it there

**Comment by Jude-Gideon** [comment]
> the hack works just go on the join page and use it there

Yes I know?

**Comment by mungK11** [comment]
ok

**Review by Hlav2022 — APPROVED** [review]

**Review by Hlav2022 — APPROVED** [review]

**Comment by staminupscho** [comment]
how do i use them

**Comment by rxzyx** [comment]
Not needed

**Pull request closed without merging**
