### PR TITLE
rzxyx → rxzyx

### PR DESCRIPTION
**Pull request by NathanBollard**
Fixes 2 broken links from #239, changes the descriptions of Set-Toys.js and Set-Toys-Per-Question.js in README.md to fit the other descriptions, and more.

### CODE REVIEW

**Comment by ZackiBoiz** [comment]
Again, my fault. Sorry!

**Review by ZackiBoiz — APPROVED** [review]

**Comment by NathanBollard** [comment]
> Again, my fault. Sorry!

You're fine!

**Review by iParadoxian — APPROVED** [review]
LGTM. No broken links.

**Comment by ZackiBoiz** [comment]
> LGTM

In the current `README.md` the Santa's Workshop hacks links are broken

**Comment by ZackiBoiz** [comment]
As in "typo"

**Pull request merged**
