### PR TITLE
Create Set Custom Blooks.js

### PR DESCRIPTION
**Pull request by ZackiBoiz**
Set your custom Blooks. This can be difficult to use, as it requires ids for custom blooks.

Video:
[hack.webm](https://user-images.githubusercontent.com/95724562/198127152-f6b584cd-30a3-401e-9f34-813133774bf0.webm)

### CODE REVIEW

**Comment by ZackiBoiz** [comment]
Sorry for the bad quality on the video.

**Comment by Wilke000** [comment]
Whoa that’s cool

**Comment by rxzyx** [comment]
Please add this into README.MD. Although this hack will be hard to use, I will accept it.

**Comment by Wilke000** [comment]
Wait how do you find the ids

**Pull request merged**
