### PR TITLE
Merge Request

### PR DESCRIPTION
**Pull request by NathanBollard**
## Introduction
Hello. I've been working on a fork to merge to [rxzyx/Blooket-Hacks](https://github.com/rxzyx/Blooket-Hacks). It is now finished, and reading for merging.

## Changes
- Created .github/ISSUE_TEMPLATE/question.md
- Updated .github/ISSUE_TEMPLATE/bug_report.md
- Updated README.md
- Created Café/Stock Unlimited Food.js
- Created Café/Max Level Food.js
- Created Café/Get Cash.js
- Deleted Cafe directory

## Fork
[NathanBollard/Blooket-Hacks](https://github.com/NathanBollard/Blooket-Hacks)

### CODE REVIEW

**Comment by VillainsRule4000** [comment]
Naming it Cafe with the little letter makes it harder for the computer to understand on programs such as VScode.
Also, the Issues are not for questions.

I find this a useless PR.

**Comment by rxzyx** [comment]
> Naming it Cafe with the little letter makes it harder for the computer to understand on programs such as VScode. Also, the Issues are not for questions.
> 
> I find this a useless PR.

True.

**Comment by ZackiBoiz** [comment]
yeah, and Read Me.md doesn't display ok the main repo page

**Comment by NathanBollard** [comment]
That's why I reverted it back to README.md

**Comment by NathanBollard** [comment]
> yeah, and Read Me.md doesn't display ok the main repo page

That's why I reverted it back to "README.md".

**Pull request closed without merging**
