### PR TITLE
stuffs

### PR DESCRIPTION
**Pull request by VillainsRule4000**
:)

### CODE REVIEW

**Comment by NathanBollard** [comment]
> no more candy q

I don't think we should merge [caf99d9](https://github.com/rxzyx/Blooket-Hacks/pull/185/commits/caf99d91c9b5a0af2c458450e499c533ebaa2236). That edit is unneeded, and it would be more work to retrieve it next year.

**Comment by VillainsRule4000** [comment]
They're the same stuff as Gold Quest, it isn't hard. Can you code? All your contributions are renaming files lmao

**Comment by ZackiBoiz** [comment]
> They're the same stuff as Gold Quest, it isn't hard. Can you code? All your contributions are renaming files lmao

It is true that they are the same as GQ. Lol

**Comment by ZackiBoiz** [comment]
It's just that the old GQ ESP doesn't work with CQ

**Comment by NathanBollard** [comment]
> It's just that the old GQ ESP doesn't work with CQ

That's what I'm trying to say. I suggest just leaving that edit out.

**Comment by VillainsRule4000** [comment]
I made the ESP, I can find it easily in my own repo.

**Comment by BlooketHeck** [comment]
@VillainsRule4000 where did you learn how to code?

**Comment by VillainsRule4000** [comment]
self-teaching

**Comment by BlooketHeck** [comment]
> self-teaching

Ok, I hear basically everybody say that. How do you self-teach?

**Comment by BlooketHeck** [comment]
Also, I agree [caf99d9](https://github.com/rxzyx/Blooket-Hacks/pull/185/commits/caf99d91c9b5a0af2c458450e499c533ebaa2236)

**Comment by VillainsRule4000** [comment]
@BlooketHeck
you look at code
you get confused
you google everything you're confused about
you know code

**Comment by BlooketHeck** [comment]
> @BlooketHeck you look at code you get confused you google everything you're confused about you know code

Amen

**Comment by rxzyx** [comment]
Bro tried to sneak in the "credit to VillainsRule4000" lol

**Comment by VillainsRule4000** [comment]
I'm planing to add some stuff later

**Comment by VillainsRule4000** [comment]
would have been part of the PR

**Comment by NathanBollard** [comment]
what

**Pull request merged**
