### PR TITLE
⚠️ READ BEFORE PULL REQUEST ⚠️

### PR DESCRIPTION
**Pull request by NathanBollard**
## Bug Fix(es)
**First...**

1. Re-test the hack in the latest version.
2. Check if there are any other Pull Requests that fix the bug.

**If these have been done, open your Pull Request and...**

1. Specify the hack(s) you've made.
2. Show a video for proof it works.

## Making a Screen Recording
* Mac > Shift + Cmd ⌘ + 5
* Windows > ⊞ Win + Alt + R
* Chromebook > Shift + Ctrl +

### CODE REVIEW

**Comment by NathanBollard** [comment]
I'm asking for you to pin this, like #156. If you want you could also merge it so it's cool

**Comment by NathanBollard** [comment]
Oh, sorry! I meant to put [a8e8e3d](https://github.com/rxzyx/Blooket-Hacks/pull/207/commits/a8e8e3d8167b56632b0a3c5439b2b2822315545d) in another Pull Request. I did not mean to add [ee37ea6](https://github.com/rxzyx/Blooket-Hacks/pull/207/commits/ee37ea69db44338cda264045b7cac3c5506df40a), either.

**Comment by rxzyx** [comment]
Can't pin a PR.

**Comment by NathanBollard** [comment]
> Can't pin a PR.

Oh, sorry.

**Comment by NathanBollard** [comment]
> 🤣 bro copypasted my stuff lol

For your information, I did not copy and paste from #156.

**Pull request merged**
