### PR TITLE
Renaming lots more things similar to #167

### PR DESCRIPTION
**Pull request by BlooketHeck**
Sorry I keep making so many pulls on renaming things.

### CODE REVIEW

**Comment by Wilke000** [comment]
Lol that’s a lot

**Comment by NathanBollard** [comment]
This should be merged.

**Comment by BlooketHeck** [comment]
> This should be merged.

Thanks!

**Comment by NathanBollard** [comment]
#167

**Comment by BlooketHeck** [comment]
> #167 has these same changes, but even more, including additions.

That is true

**Pull request merged**
