### PR TITLE
Create Get-Folder.js

### PR DESCRIPTION
**Pull request by ZackiBoiz**
Create a folder in the My-Sets page without the Blooket Plus plan.

### CODE REVIEW

**Comment by NathanBollard** [comment]
@ZackiBoiz, I recreated Get-Folder.js in #214, but I updated [README.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/README.md) to go with it. Don't worry though, since I still credited you. If mine is merged, it'll still have your name on the main page. Do you want to close this?

**Comment by VillainsRule4000** [comment]
> @ZackiBoiz, I recreated Get-Folder.js in #214, but I updated [README.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/README.md) to go with it. Don't worry though, since I still credited you. If mine is merged, it'll still have your name on the main page. Do you want to close this?

🤣 you just want all the commit fame. what an L

**Comment by ZackiBoiz** [comment]
> @ZackiBoiz, I recreated Get-Folder.js in #214, but I updated [README.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/README.md) to go with it. Don't worry though, since I still credited you. If mine is merged, it'll still have your name on the main page. Do you want to close this?

Oh, I'm so stupid. I didn't add a `README.md` update.

**Comment by NathanBollard** [comment]
> > @ZackiBoiz, I recreated Get-Folder.js in #214, but I updated [README.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/README.md) to go with it. Don't worry though, since I still credited you. If mine is merged, it'll still have your name on the main page. Do you want to close this?
> 
> 🤣 you just want all the commit fame. what an L

Wdym? Look at [NathanBollard:main](https://github.com/NathanBollard/Blooket-Hacks). It literally has his name on the main page.

**Comment by NathanBollard** [comment]
> > @ZackiBoiz, I recreated Get-Folder.js in #214, but I updated [README.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/README.md) to go with it. Don't worry though, since I still credited you. If mine is merged, it'll still have your name on the main page. Do you want to close this?
> 
> Oh, I'm so stupid. I didn't add a `README.md` update.

I can make one, but you're not stupid.

**Pull request merged**
