### PR TITLE
Update Request

### PR DESCRIPTION
**Pull request by NathanBollard**
My fork has 23 extra commits, and I am requesting for all of them to be added to this repository.

### CODE REVIEW

**Comment by NathanBollard** [comment]
I'd also like to request an update for this repository's description from "The absolute best Blooket hack there is." to 'The absolute best Blooket hacks there are.'

By the way, congratulations on 100+ stars on this repository!

**Comment by BlooketHeck** [comment]
Does Auto-Answer.js work? if it does that would be an insane hack

**Comment by BlooketHeck** [comment]
> Does Auto-Answer.js work? if it does that would be an insane hack

Ok, this might be my favorite hack
[Screen recording 2022-11-03 7.27.40 PM.webm](https://user-images.githubusercontent.com/94115787/199854134-afe436cb-5f8c-4b0c-8594-e384fe3152d4.webm)

**Comment by NathanBollard** [comment]
> > Does Auto-Answer.js work? if it does that would be an insane hack
> 
> Ok, this might be my favorite hack [Screen recording 2022-11-03 7.27.40 PM.webm](https://user-images.githubusercontent.com/94115787/199854134-afe436cb-5f8c-4b0c-8594-e384fe3152d4.webm)

Thank you!

**Comment by NathanBollard** [comment]
> Does Auto-Answer.js work? if it does that would be an insane hack

Yes, it does work.

**Comment by NathanBollard** [comment]
> > Does Auto-Answer.js work? if it does that would be an insane hack
> 
> Ok, this might be my favorite hack [Screen recording 2022-11-03 7.27.40 PM.webm](https://user-images.githubusercontent.com/94115787/199854134-afe436cb-5f8c-4b0c-8594-e384fe3152d4.webm)

Thank you!

**Comment by NathanBollard** [comment]
I just wanted to mention that [README.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/README.md) has an invalid link, and that [a0ebd45](https://github.com/rxzyx/Blooket-Hacks/pull/167/commits/a0ebd451c923e9e3b1e7fb272c416f257d51a5ce) fixes that, which that commit is in this pull request.

**Comment by rxzyx** [comment]
Did you make the two hacks?

**Comment by rxzyx** [comment]
“Collect Max Tokens and Tokens”, script availability is unknown. I will close it for now until you can fix errors and explain

**Comment by NathanBollard** [comment]
> “Collect Max Tokens and Tokens”, script availability is unknown. I will close it for now until you can fix errors and explain

The "Collect Max Tokens and Tokens.js" was from "Add Tokens.js", and I now just renamed it to "Add Tokens And XP.js". You can merge it in #168.

**Comment by rxzyx** [comment]
Not what I meant. Also top question ignored?

**Comment by NathanBollard** [comment]
> Did you make the two hacks?
> Not what I meant. Also top question ignored?

Sorry. I answered that in [this comment](https://github.com/rxzyx/Blooket-Hacks/pull/168#issuecomment-1303648108). Here was the message:

## 

> Who made auto answer and set candy? I will merge when you say.

Auto-Answer.js was made from a friend of mine, and I was given permission to put it in this repository. Set Candy.js has the same exact coding as Set Gold.js, because Set Gold.js works on Gold Quest and Candy Quest.

_Originally posted by @NathanBollard in https://github.com/rxzyx/Blooket-Hacks/issues/168#issuecomment-1303648108_

**Comment by VillainsRule4000** [comment]
this pr is kinda dumb ngl

**Comment by gimmy74** [comment]
> this pr is kinda dumb ngl

ong smh

**Pull request closed without merging**
