### PR TITLE
Update Request Copy

### PR DESCRIPTION
**Pull request by NathanBollard**
My fork has 26 extra commits, and I am requesting for all of them to be added to this repository. (I have fixed the issues you mentioned, @rxzyx)

## Tags
#167

### CODE REVIEW

**Comment by rxzyx** [comment]
Who made auto answer and set candy? I will merge when you say.

**Comment by BlooketHeck** [comment]
@rxzyx [Set Gold.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Gold%20Quest/Set%20Gold.js) works in candy quest

**Comment by BlooketHeck** [comment]
> @rxzyx [Set Gold.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Gold%20Quest/Set%20Gold.js) works in candy quest

Also, I just checked a difference checker and the 2 files are identical.

**Comment by NathanBollard** [comment]
> Who made auto answer and set candy? I will merge when you say.

Auto-Answer.js was made from a friend of mine, and I was given permission to put it in this repository. Set Candy.js has the same exact coding as Set Gold.js, because Set Gold.js works on Gold Quest and Candy Quest.

**Comment by NathanBollard** [comment]
Thank you for your time and actions!

**Comment by NathanBollard** [comment]
Thank you!

**Pull request merged**
