### PR TITLE
Formatting Fix

### PR DESCRIPTION
**Pull request by NathanBollard**
I fixed the formatting for [CODE_OF_CONDUCT.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/CODE_OF_CONDUCT.md), [CONTRIBUTING.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/CONTRIBUTING.md), [LICENSE](https://github.com/rxzyx/Blooket-Hacks/blob/main/LICENSE), [PULL_REQUEST_TEMPLATE.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/PULL_REQUEST_TEMPLATE.md), and a little bit of [README.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/README.md). (Don't worry, none of the actual text was changed.) I also thought it was a little confusing with [Manipulate-Plus.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Default-Scripts/Manipulate-Plus.js), (especially with [Get-Folder.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Default-Scripts/Get-Folder.js)), so I renamed [Manipulate-Plus.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Default-Scripts/Manipulate-Plus.js) and moved it along with [Get-Folder.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Default-Scripts/Get-Folder.js) to a new folder: [Plus](https://github.com/rxzyx/Blooket-Hacks/tree/main/Default-Scripts/Plus). (I also updated [README.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/README.md) to those updates.)

### CODE REVIEW

**Comment by NathanBollard** [comment]
Tell me if I missed anything!

**Comment by ZackiBoiz** [comment]
> I fixed the formatting for [CODE_OF_CONDUCT.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/CODE_OF_CONDUCT.md), [CONTRIBUTING.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/CONTRIBUTING.md), [LICENSE](https://github.com/rxzyx/Blooket-Hacks/blob/main/LICENSE), [PULL_REQUEST_TEMPLATE.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/PULL_REQUEST_TEMPLATE.md), and a little bit of [README.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/README.md). (Don't worry, none of the actual text was changed.) I also thought it was a little confusing with [Manipulate-Plus.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Default-Scripts/Manipulate-Plus.js), (especially with [Get-Folder.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Default-Scripts/Get-Folder.js)), so I renamed [Manipulate-Plus.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Default-Scripts/Manipulate-Plus.js) and moved it along with [Get-Folder.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Default-Scripts/Get-Folder.js) to a new folder: [Plus](https://github.com/rxzyx/Blooket-Hacks/tree/main/Default-Scripts/Plus). (I also updated [README.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/README.md) to those updates.)

The first 2 commits aren't a "host" thing

**Comment by rxzyx** [comment]
^

**Comment by NathanBollard** [comment]
> > I fixed the formatting for [CODE_OF_CONDUCT.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/CODE_OF_CONDUCT.md), [CONTRIBUTING.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/CONTRIBUTING.md), [LICENSE](https://github.com/rxzyx/Blooket-Hacks/blob/main/LICENSE), [PULL_REQUEST_TEMPLATE.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/PULL_REQUEST_TEMPLATE.md), and a little bit of [README.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/README.md). (Don't worry, none of the actual text was changed.) I also thought it was a little confusing with [Manipulate-Plus.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Default-Scripts/Manipulate-Plus.js), (especially with [Get-Folder.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Default-Scripts/Get-Folder.js)), so I renamed [Manipulate-Plus.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Default-Scripts/Manipulate-Plus.js) and moved it along with [Get-Folder.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Default-Scripts/Get-Folder.js) to a new folder: [Plus](https://github.com/rxzyx/Blooket-Hacks/tree/main/Default-Scripts/Plus). (I also updated [README.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/README.md) to those updates.)
> 
> The first 2 commits aren't a "host" thing

oh im stupid i meant to make it say plus
should i redo this pr with that fixed?

**Pull request closed without merging**
