### PR TITLE
Update Request

### PR DESCRIPTION
**Pull request by NathanBollard**
My fork has 5 commits, and I am requesting for those commits to be added to this repository.

Basically, it just renames the files in Blook Rush, and updates README.md. I know that I spam pull requests a lot, but this could be an actual good change. (Hereby, this pull request's commits also fix an invalid link in README.md)

I'd also like to mention one more thing, about the repository's description. I want to request a description change from "The absolute best Blooket hack there is." to 'The absolute best Blooket hacks there are.'

Thank you for your time and actions.

### CODE REVIEW

**Comment by BlooketHeck** [comment]
I feel like [112c9c7](https://github.com/rxzyx/Blooket-Hacks/pull/192/commits/112c9c75117fb3e8612a45a428f3124d1cffc868) is uneeded

**Comment by ZackiBoiz** [comment]
True

> I feel like [112c9c7](https://github.com/rxzyx/Blooket-Hacks/pull/192/commits/112c9c75117fb3e8612a45a428f3124d1cffc868) is uneeded

**Comment by BlooketHeck** [comment]
Also, you keep making lots of pulls on editing readme and renaming things, just make one pull.

**Comment by NathanBollard** [comment]
> Also, you keep making lots of pulls on editing readme and renaming things, just make one pull.

Bro, you used to do a bunch of them.

**Comment by NathanBollard** [comment]
> I feel like [112c9c7](https://github.com/rxzyx/Blooket-Hacks/pull/192/commits/112c9c75117fb3e8612a45a428f3124d1cffc868) is uneeded

Why? [112c9c7](https://github.com/rxzyx/Blooket-Hacks/pull/192/commits/112c9c75117fb3e8612a45a428f3124d1cffc868) fixes invalid links, and updates with the renames.

**Comment by rxzyx** [comment]
I feel like it’s enough “re-names”.

**Comment by NathanBollard** [comment]
> I feel like it’s enough “re-names”.

@BlooketHeck did most of the renames, but it'll be the last two for the made-up "Set" rule. All the "Add"s (discluding [Add Mega Bots.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Factory/Add%20Mega%20Bots.js)) and "Get"s are renamed to "Set", except those two: [Get Blooks.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Blook%20Rush/Get%20Blooks.js) and [Get Defense.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Blook%20Rush/Get%20Defense.js). Plus, newcomers who are looking for working [Blook Rush](https://github.com/rxzyx/Blooket-Hacks/tree/main/Blook%20Rush) hacks, it would look more like it works, since the last edit wasn't over 5 months ago. It also updates more than you think in [README.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/README.md). In [README.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/README.md), there was NO list of hacks for [Blook Rush](https://github.com/rxzyx/Blooket-Hacks/tree/main/Blook%20Rush) nor [Crazy Kingdom](https://github.com/rxzyx/Blooket-Hacks/tree/main/Crazy%20Kingdom). I added them, and organized all the gamemode categories in the current Blooket host order. I also alphabetized all the hacks for each category, and updated <i>most</i> of the descriptions. For the people who look for [Blook Rush](https://github.com/rxzyx/Blooket-Hacks/tree/main/Blook%20Rush) hacks, it looks more appealing to them since it was recently updated, and let's them know it more likely to work than if it was updated last over 5 months ago. Those are some of the reasons why you should merge this pull request. (Sorry for the late response.)

**Comment by VillainsRule4000** [comment]
for the love of god you wrote a paragraph :rofl:
also we don't care about visual updates LMAO, if they work they work

**Comment by NathanBollard** [comment]
> for the love of god you wrote a paragraph 🤣 also we don't care about visual updates LMAO, if they work they work

What do you mean by "if they work they work"?

**Pull request closed without merging**
