### PR TITLE
Nothing wrong but request

### PR DESCRIPTION
**Pull request by blixzy1**
could you make a code so when you put it in you are promised something better than a rare in all of the packs

### CODE REVIEW

**Comment by ZackiBoiz** [comment]
False issue. Join the discord for suggestions

**Comment by Wilke000** [comment]
Shoot that’s a lot of changes!
Pull request this into Minesraft’s repo and Mines might add some

**Comment by VillainsRule4000** [comment]
this is stupid. bro clicked some random shit not knowing what they're doing.

**Comment by Wilke000** [comment]
Wdym

**Comment by Angelio-Mustachio-Coder** [comment]
idiot. you can't improve chances, thats server based, false pull.

**Comment by rxzyx** [comment]
^

**Pull request closed without merging**
