### PR TITLE
Updated a few things

### PR DESCRIPTION
**Pull request by VillainsRule4000**
List:
README.md - this was in both body HTML and markdown format, which are NOT supposed to be mixed.
**Don't merge this yet, I'm still working on a few more things.**

### CODE REVIEW

**Comment by rxzyx** [comment]
Tampermonkey*, not Tampermokey

**Comment by rxzyx** [comment]
Also mixing HTML and Markdown is fine, I don't see the problem?

**Comment by VillainsRule4000** [comment]
@rxzyx It isn't a large issue, you can just close this...

**Comment by rxzyx** [comment]
I prefer some of the original preferences, however; I will take to account on some things you have stated if you're ok with that? (Request will be closed).

**Comment by VillainsRule4000** [comment]
@rxzyx Alright! In the README, you need to update the link to the Tampermokey Anti-Ban

**Comment by rxzyx** [comment]
Oh ye thx

**Pull request closed without merging**
