### PR TITLE
Fix typo in README.md and change name of "Health Hack.js" to "Set Health.js"

### PR DESCRIPTION
**Pull request by BlooketHeck**
there was a typo for the [instant win](https://github.com/rxzyx/Blooket-Hacks/blob/main/Racing/Instant%20Win.js) in the [README.md](https://github.com/rxzyx/Blooket-Hacks/blob/main/README.md) (sorry for all the rename pull requests)

### CODE REVIEW

**Comment by ZackiBoiz** [comment]
Bro, why are you making so many "rename" pulls? Just make one pull.

**Comment by BlooketHeck** [comment]
> Bro, why are you making so many "rename" pulls? Just make one pull.

Oh, ok

**Comment by rxzyx** [comment]
> Bro, why are you making so many "rename" pulls? Just make one pull.

^^^^

**Comment by rxzyx** [comment]
> Bro, why are you making so many "rename" pulls? Just make one pull.

^^^^

**Pull request merged**
