### PR TITLE
Update Request

### PR DESCRIPTION
**Pull request by NathanBollard**
My fork has 4 extra commits, and I am requesting for all of them to be added to this repository.

### CODE REVIEW

**Comment by VillainsRule4000** [comment]
Leave an unobfucated version so that I can make it work on Royale.

**Comment by VillainsRule4000** [comment]
Honestly, this PR is overall useless.

**Comment by ZackiBoiz** [comment]
> Honestly, this PR is overall useless.

Yeah, why 3 `README.md` updates lol

**Comment by VillainsRule4000** [comment]
yea lmao
bro can't code :skull:
imo quitting when you don't like something is cringe
like there are royale hacks, it's just harder

**Comment by rxzyx** [comment]
Again?

**Comment by NathanBollard** [comment]
> Leave an unobfucated version so that I can make it work on Royale.

No.

**Comment by VillainsRule4000** [comment]
Do you even care about the hacks working?
I suspect the unobfuscated version is something you're hiding...

**Comment by VillainsRule4000** [comment]
Send it here, I'll make a Royale fix.

**Comment by NathanBollard** [comment]
> Send it here, I'll make a Royale fix.

Send what? The code? Just look in [ef09298](https://github.com/rxzyx/Blooket-Hacks/pull/186/commits/ef09298ec68397d70e4deb03cbcf1e2696551875), a commit in this pull request.

**Pull request closed without merging**
